// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/kaisersuzaku/BE_A/models"
	mock "github.com/stretchr/testify/mock"
)

// IFillBallContainerService is an autogenerated mock type for the IFillBallContainerService type
type IFillBallContainerService struct {
	mock.Mock
}

// IsContainerFull provides a mock function with given fields: ctx, req
func (_m *IFillBallContainerService) IsContainerFull(ctx context.Context, req models.FillBallContainerReq) models.FillBallContainerResp {
	ret := _m.Called(ctx, req)

	var r0 models.FillBallContainerResp
	if rf, ok := ret.Get(0).(func(context.Context, models.FillBallContainerReq) models.FillBallContainerResp); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(models.FillBallContainerResp)
	}

	return r0
}

// ValidateRequest provides a mock function with given fields: ctx, req
func (_m *IFillBallContainerService) ValidateRequest(ctx context.Context, req models.FillBallContainerReq) models.RespError {
	ret := _m.Called(ctx, req)

	var r0 models.RespError
	if rf, ok := ret.Get(0).(func(context.Context, models.FillBallContainerReq) models.RespError); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(models.RespError)
	}

	return r0
}
