// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/kaisersuzaku/BE_A/models"
	mock "github.com/stretchr/testify/mock"
)

// IOrderProductService is an autogenerated mock type for the IOrderProductService type
type IOrderProductService struct {
	mock.Mock
}

// OrderProduct provides a mock function with given fields: ctx, req
func (_m *IOrderProductService) OrderProduct(ctx context.Context, req models.OrderProductReq) (models.OrderProductResp, models.RespError) {
	ret := _m.Called(ctx, req)

	var r0 models.OrderProductResp
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderProductReq) models.OrderProductResp); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(models.OrderProductResp)
	}

	var r1 models.RespError
	if rf, ok := ret.Get(1).(func(context.Context, models.OrderProductReq) models.RespError); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(models.RespError)
	}

	return r0, r1
}
